### PR TITLE
Edits to the VSI about page

### PR DESCRIPTION
**Pull request by hlucey**
Here are the edits to the VSI about page. @cdmauney can you take a look before this is merged?

### CODE REVIEW

**Review by cdmauney — CHANGES_REQUESTED** [review]
This sample template configures an IBM Cloud database instance and virtual server instances (VSI). Security groups are configured so that the VSI can access the IBM Cloud database instance on the  IBM Cloud database instance connection port, which is dynamically defined. Whitelisting is configured on the IBM Cloud database instance to allow access only from the VSI IP address.

**Review by cdmauney — CHANGES_REQUESTED** [review]
This sample uses chargeable services and you are charged for the time the services are deployed. Running the `terraform destroy` command deletes all resources, including the IBM Cloud database service instance. Billing for VSI and IBM Cloud database terminates on the hour. 

The last sentence isn't clear to me. Billing ends on the hour when I run the destroy command?

**Review by cdmauney — CHANGES_REQUESTED** [review]
Set the following variables before you use the template: 

* `softlayer_username` is the infrastructure user name. Go to **Access (IAM)** > **Users**, and select your name. Then, verify that the user name is listed in the VPN password section.

* `softlayer_api_key` is a classic infrastructure API key. Go to **Access (IAM)** > **Users**, and select your name. Then, verify that a classic infrastructure API key is included in the API keys section. If you don't have one already, go to the [IBM Cloud API keys page](https://cloud.ibm.com/iam/apikeys) and create one.
* `ibmcloud_api_key` is an API key used for IBM Cloud services. You can create one from the [IBM Cloud API keys page](https://cloud.ibm.com/iam/apikeys).

**Review by cdmauney — CHANGES_REQUESTED** [review]
The example is deployed in the eu-gb region. The `region` parameter in the `provider.tf` file must be set to the same region as the IBM Cloud database instance that it's deployed in, as defined by the `location` parameter on the ibm_database resource.

**Review by cdmauney — CHANGES_REQUESTED** [review]
The hostname for the virtual machine, for example, vm1.

The domain for the virtual machine, for example, domain.dev. 

The data center to create the VSI, for example, dal13. To get a list of all data centers, run the `ic sl vs options` command. 

The location in which to deploy the instance.

The default password for the admin user.

The new database user name. 

**Note**: For more information  about the deployment values, see the following links:

**Review by cdmauney — CHANGES_REQUESTED** [review]
The composed connection string for the default admin ID for the deployed IBM Cloud database PostgreSQL database is displayed. Connection string usage depends on the type of IBM Cloud database service that is deployed. There might be multiple strings for different hosts in the database cluster. See the [IBM Cloud database documentation](https://cloud.ibm.com/docs/services/databases-for-etcd?topic=databases-for-etcd-connection-strings#connection-strings) for information about the use of connection strings.

**Comment by cdmauney** [comment]
@hlucey Review comments above.

**Comment by hlucey** [comment]
ready to merge

**Pull request merged**
