### PR TITLE
Edits to VSI deployment values

### PR DESCRIPTION
**Pull request by hlucey**
Here are our proposed changes to the VSI deployment values. Before you merge, we would like our editor @cdmauney to review.

### CODE REVIEW

**Review by cdmauney — CHANGES_REQUESTED** [review]
"Enter your classic infrastructure user name. Go to https://cloud.ibm.com/iam/users/, select your name, and find your user name in the VPN password section."

**Comment by hlucey** [comment]
Ready to merge.

**Comment by cdmauney** [comment]
@hlucey My fault. Just so we're consistent with other updates, let's change to:

"Enter your classic infrastructure user name. Go to **Access (IAM)** > **Users**, and select your name. Then, find your user name in the VPN password section."

**Comment by hlucey** [comment]
Ready to merge

**Pull request merged**
